Repository GSG-FC02/ToDoApp-Amira-Omar, pull requests merged in 2021-03, with the labels that each got.

#6 add html css js files
  images/background.jpg
  images/fav-icon.png
  index.html
  script.js
  style.css
Labels: awaiting-review

#7 added html code
  index.html
Labels: Done

#8 added css code
  style.css
Labels: Done

#10 add initial values
  index.html
  script.js
Labels: Done

#12 add js code
  script.js
Labels: Done, awaiting-review

#13 1 update font
  index.html
Labels: awaiting-review
